### ISSUE TITLE
Can you build project for Visual Studio 2017

### ISSUE THREAD

**Issue by ellinde** [cruppstahl/upscaledb#104]
Hi) You made very nice stuff)))
But... Can you build the project for actual Visual Studio 2017? It should be cool)

**Comment by cruppstahl** [comment]
Sorry for the late reply. i don't have a copy of MSVC2017, therefore I cannot provide you a build. But you should be able to migrate the existing solution files (in win32/msvc2013) to MSVC2017. Here are prebuilt win32 libraries, you might able to use some of them: https://github.com/cruppstahl/upscaledb-alien
