### ISSUE TITLE
Compile server library

### ISSUE THREAD

**Issue by rbwilcoxon11** [cruppstahl/upscaledb#113]
I have configured and can run the base upscaledb library, but I can't quite figure out how to compile the server library.

When I try to run the server without linking to upsserver:

cd samples && gcc server1.c -o server.out -lupscaledb
Undefined symbols for architecture x86_64:
  "_ups_srv_add_env", referenced from:
      _main in server1-ed9831.o
  "_ups_srv_close", referenced from:
      _main in server1-ed9831.o
  "_ups_srv_init", referenced from:
      _main in server1-ed9831.o

But, when I try to run with linking to upsserver:

cd samples && gcc server1.c -o server.out -lupscaledb -lupsserver
ld: library not found for -lupsserver

I also noticed that only the following libs got built (and subsequently installed):

ls src/.libs
libupscaledb.0.dylib	libupscaledb.dylib	libupscaledb.lai
libupscaledb.a		libupscaledb.la

I think I'm just missing a target for the makefile, but I am unfamiliar with autoconf... I tried running make in the src directory, and the src/5server directory with no luck...

**Comment by rbwilcoxon11** [comment]
Okay, after digging I realized it is because I didn't have google protocol buffer installed. Reconfigured and remade.

I had to make a change to upserver.cc to get it to compile though. For boost version 1.67, I got the following error:

upsserver.cc:1976:22: error: invalid operands to binary expression ('const boost::system::error_code' and
      'int')
  if (unlikely(error != 0) || bytes_transferred == 0) {
               ~~~~~ ^  ~
../0root/root.h:70:43: note: expanded from macro 'unlikely'
#   define unlikely(x) __builtin_expect ((x), 0)

I could get around this if I change error to error.value(). It allows me to run the server example, but now I get 51 unit test errors, mainly of this variety

Remote/createCloseTest
-------------------------------------------------------------------------------
remote.cpp:1234
...............................................................................

remote.cpp:101: FAILED:
  REQUIRE( 0 == ups_env_create(&env, "ups://localhost:8989/test.db", 0, 0664, 0) )
with expansion:
  0 == -20

**Comment by rbwilcoxon11** [comment]
Okay, changed upsserver.cc:1976 from

if (unlikely(error != 0) || bytes_transferred == 0) {

to
if (unlikely(error.value() != boost::system::errc::success) || bytes_transferred == 0) {

and those errors went away, but now i have 10 errors, mainly of the variety 

Remote/cursorInsertFindEraseUserallocTest
-------------------------------------------------------------------------------
remote.cpp:1378
...............................................................................

remote.cpp:797: FAILED:
  REQUIRE( 0ull == keycount )
with expansion:
  0
  ==
  18446744073709551615 (0xffffffffffffffff)

and

-------------------------------------------------------------------------------
Remote/cursorInsertFindEraseRecno64Test
-------------------------------------------------------------------------------
remote.cpp:1384
...............................................................................

remote.cpp:674: FAILED:
  REQUIRE( 2ull == keycount )
with expansion

**Comment by cruppstahl** [comment]
Thanks for the info. I know about the unittest failures - will take care of them when I have some time. Feel free to submit a patch regarding boost - however it should continue working with older versions (1.45 and above). They keep changing their APIs frequently...
