### ISSUE TITLE
how to join tables?

### ISSUE THREAD

**Issue by 0x410c** [cruppstahl/upscaledb#116]
i want to join two tables to find all matchin entries, any alternative if join not available?

**Comment by cruppstahl** [comment]
For full table scans you can use a nested loop with cursors. For optimization, the outer loop should have a higher selectivity, i.e. it should return fewer results than the inner loop.

See the sample env2.c line 225 for a join based on the key values, i.e. without a full table scan. The outer loop is implemented with a cursor. The inner lookup uses ham_db_find/ham_cursor_find.
