### ISSUE TITLE
Production and performance query

### ISSUE THREAD

**Issue by 0x410c** [cruppstahl/upscaledb#117]
regarding last update to the library was in 2016, is this db can be used in production? also do you think upscale db is still the fastest key value database out there, if not which are the others?

**Comment by cruppstahl** [comment]
You can use it in production, but it's no longer maintained. 
Regarding other databases - it mostly depends on your use case, so it's hard to give general recommendations. But if you choose either sqlite or leveldb then for most cases you should be fine.
