### ISSUE TITLE
3rd party dependecies under Linux

### ISSUE THREAD

**Issue by cflaviu** [cruppstahl/upscaledb#128]
Hi Christoph,

I'm trying linking upscale library but I'm getting linking errors. What are the 3rd party libraries that should be linked under Linux? Maybe those libraries would be helpful in documentation.

PS I'm trying using cista serialization library for storing values in db. It is a nice library competing against protobuffer, flatbuffer, etc.

Regards
Flaviu

**Comment by cflaviu** [comment]
After several search on stackoverflow I found all dependecies:

- /usr/local/lib/libupscaledb.a
- boost_thread
- crypto
- dl
- pthread
- ssl
- z

**Comment by cruppstahl** [comment]
Hi Flaviu,

it depends which features you use... the file `configure.ac` lists all dependencies; it might be helpful (although you have to navigate through the script a bit).

BR
Christoph

**Comment by cflaviu** [comment]
Using Qbs build tool, I needed all dependent library names. 

Thank you
Flaviu
