### ISSUE TITLE
configure fails to find correct boost_major_version on boost 1.58

### ISSUE THREAD

**Issue by Rainmaker52** [cruppstahl/upscaledb#59]
When compiling hamsterdb 2.1.11 on ubuntu 15.10, the configure fails with 
checking whether the compiler supports GCC C++ ABI name demangling... yes
checking for Boost headers version >= 1.53.0... yes
checking for Boost's header version... 

configure: error: invalid value: boost_major_version=

Boost library is installed (1.58).

I'm not sure where this is going wrong, but $boost_cv_lib_version contains an empty string after the test in configure (around line 17338).

Quick 'n dirty workaround is to manually assign "158" to boost_cv_lib_version after the test.

This allows hamsterdb to compile successfully.

/usr/include/boost/version.hpp:
//  Boost version.hpp configuration header file  ------------------------------//

//  (C) Copyright John maddock 1999. Distributed under the Boost
//  Software License, Version 1.0. (See accompanying file
//  LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

//  See http://www.boost.org/libs/config for documentation

#ifndef BOOST_VERSION_HPP
#define BOOST_VERSION_HPP

//
//  Caution: this is the only Boost header that is guaranteed
//  to change with every Boost release. Including this header
//  will cause a recompile every time a new Boost version is
//  used.
//
//  BOOST_VERSION % 100 is the patch level
//  BOOST_VERSION / 100 % 1000 is the minor version
//  BOOST_VERSION / 100000 is the major version

#define BOOST_VERSION 105800

//
//  BOOST_LIB_VERSION must be defined to be the same as BOOST_VERSION
//  but as a *string* in the form "x_y[_z]" where x is the major version
//  number, y is the minor version number, and z is the patch level if not 0.
//  This is used by <config/auto_link.hpp> to select which library version to link to.

#define BOOST_LIB_VERSION "1_58"

#endif

**Comment by cruppstahl** [comment]
OK, thanks. Will look into it soon-ish.

**Comment by cruppstahl** [comment]
Fixed by upgrading to a newer boost.m4 file
