### ISSUE TITLE
include path is ham instead of ups

### ISSUE THREAD

**Issue by wshager** [cruppstahl/upscaledb#67]
It seems the path created in /usr/local/include is 'ham'. That probably should be updated.

**Comment by wshager** [comment]
I find it discouraging that when I search this github repo for 'ham', a lot of files are found.

**Comment by wshager** [comment]
@cruppstahl the HAM string (pun intended) is also written to the db file. Anyway, I'm all set up and good to go, and that IS encouraging.

**Comment by cruppstahl** [comment]
The "HAM" string is just a header identifier. The others are now fixed.
