### ISSUE TITLE
Make API searchable

### ISSUE THREAD

**Issue by wshager** [cruppstahl/upscaledb#68]
It's very hard to use the API without guidance. Please provide the full list of functions or a search option.

**Comment by wshager** [comment]
I found the 'file' link in documentation somewhat helpful...

**Comment by cruppstahl** [comment]
Good idea, I'll add this to my TODO list for the webpage.

2016-01-20 13:49 GMT+01:00 Wouter Hager <notifications@github.com>:

**Comment by wshager** [comment]
@cruppstahl great! I should've written "I find it very hard to use the API". I'm fairly new to C.

**Comment by cruppstahl** [comment]
I tried to provide many samples, a tutorial and also have sufficiently good documentation in the header file (at least for an open source project). I think the samples might be the best starting point. If C becomes too frustrating then feel free to drop me a mail (chris@crupp.de), I don't mind helping.
