### ISSUE TITLE
error while loading shared libraries: libupscaledb.so.1

### ISSUE THREAD

**Issue by wshager** [cruppstahl/upscaledb#69]
I get an error when trying to execute compiled code: error while loading shared libraries: libupscaledb.so.1: cannot open shared object file: No such file or directory.

**Comment by cruppstahl** [comment]
The file should be built in src/.libs, and installed in /usr/local/lib as a
symbolic link. I have seen some systems where /usr/local/lib is not in the
search path for the library loader (on ubuntu add the path to
/etc/ld.conf.d/FILE) and call ldconfig).

PS: thanks for the other issues, I'm working on them...

2016-01-20 14:27 GMT+01:00 Wouter Hager <notifications@github.com>:

**Comment by wshager** [comment]
@cruppstahl simply calling `ldconfig` was enough, thanks.
