### ISSUE TITLE
Build on arm

### ISSUE THREAD

**Issue by MrApe** [cruppstahl/upscaledb#75]
HI, I tried to build on arm (beaglebone) bit realized that simd is used:

`gcc: error: unrecognized command line option '-msse4'`

So I called `./configure --disable-simd`. However, simdcomp in 3rdparty folder is still built giving the error above. 

Is upscale limited to SSE capable processors?

Thanks. Jonas

**Comment by cruppstahl** [comment]
Hi Jonas,

I'll fix this in the next few days. Thanks for reporting.

2016-03-15 17:39 GMT+01:00 Jonas Schwartze <notifications@github.com>:

**Comment by cruppstahl** [comment]
This should be fixed now. Please pull the master branch and configure with --disable-simd. I did not test w/ ARM due to lack of time; it would be nice if you could provide some feedback.
