### ISSUE TITLE
Compile error "narrowing conversion of ‘-1’ from ‘int’ to ‘uint8_t {aka unsigned char}’" for 2.2.0

### ISSUE THREAD

**Issue by Rainmaker52** [cruppstahl/upscaledb#80]
I am not sure what exactly I'm doing wrong here.

I ran a ./configure, and a make. The make errors out with:

Making all in streamvbyte
make[3]: Entering directory '/sub/tank/Downloads/upscaledb-2.2.0/3rdparty/streamvbyte'
  CXX      streamvbyte.lo
streamvbyte.cc:705:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘uint8_t {aka unsigned char}’ inside { } [-Wnarrowing]
 };
 ^
streamvbyte.cc:705:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘uint8_t {aka unsigned char}’ inside { } [-Wnarrowing]
streamvbyte.cc:705:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘uint8_t {aka unsigned char}’ inside { } [-Wnarrowing]
...
streamvbyte.cc:705:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘uint8_t {aka unsigned char}’ inside { } [-Wnarrowing]
streamvbyte.cc:709:66: error: narrowing conversion of ‘18446474740605323528ul’ from ‘long unsigned int’ to ‘long long int’ inside { } [-Wnarrowing]
 static xmm_t High16To32 = {0xFFFF0B0AFFFF0908, 0xFFFF0F0EFFFF0D0C};
                                                                  ^
streamvbyte.cc:709:66: error: narrowing conversion of ‘18446479155831704844ul’ from ‘long unsigned int’ to ‘long long int’ inside { } [-Wnarrowing]
Makefile:407: recipe for target 'streamvbyte.lo' failed
make[3]: *** [streamvbyte.lo] Error 1
make[3]: Leaving directory '/sub/tank/Downloads/upscaledb-2.2.0/3rdparty/streamvbyte'
Makefile:371: recipe for target 'all-recursive' failed

**Comment by cruppstahl** [comment]
I've seen this error when compiling with c++11 enabled.

I've pushed a fix to the master branch. Please reopen if it still won't compile, and add information about your compiler (name, version etc).

**Comment by Rainmaker52** [comment]
I am using a fairly standard Linux toolchain. Have upgraded to the latest GCC in Arch Linux though:
