### ISSUE TITLE
Call For Action: "C++11"

### ISSUE THREAD

**Issue by moellney-IGI** [cruppstahl/upscaledb#84]
Dear Christoph,

in the release notes of UpscaleDB 2.2.0 you have a 
"call for action"
about the C++11 topic.

I still use HamsterDB, but want to take part in the ongoing development under the UpscaleDB.
(I'm about to buy a license :-)

The tool-chain I'm bound to is still Visual Studio 2010 Compiler (WinSDK 7.1 ....).
So there is very limited C++11 support.
The qt file:
http://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/global/qcompilerdetection.h
has a nice reliable listing of features, that work under different versions of compilers.
There they define macros: e.g. Q_COMPILER_RANGE_FOR if the compiler supports the new range for....

For VS2010 they note:
```
#    if _MSC_VER >= 1600
       /* C++11 features supported in VC10 = VC2010: */
#      define Q_COMPILER_AUTO_FUNCTION
#      define Q_COMPILER_AUTO_TYPE
#      define Q_COMPILER_DECLTYPE
#      define Q_COMPILER_EXTERN_TEMPLATES
#      define Q_COMPILER_LAMBDA
#      define Q_COMPILER_NULLPTR
#      define Q_COMPILER_RVALUE_REFS
#      define Q_COMPILER_STATIC_ASSERT
//  MSVC's library has std::initializer_list, but the compiler does not support the braces initialization
//#      define Q_COMPILER_INITIALIZER_LISTS
//#      define Q_COMPILER_UNIFORM_INIT
#    endif
```

I managed to compile UpscaleDB 2.2.0 with VS2010 using the alien files you provide for 2010 in an older git branch.
There are the about 10000 warnings, when compiling the dll..... but it seems to work.

Kind regards,
Michael

**Comment by cruppstahl** [comment]
Great, thanks for the feedback.
If 2.2.0 worked then 2.2.1 should also work with VC2010. (If not then we'll fix it.)

**Comment by moellney-IGI** [comment]
Thank you for your info.
