### ISSUE TITLE
Build Fail in OSX with Remote Database

### ISSUE THREAD

**Issue by fmgdias** [cruppstahl/upscaledb#92]
Hi,

I'm trying to compile on OSX and it does not work.

> Library

$ brew install libuv snappy protobuf boost

Warning: boost-1.61.0 already installed
Warning: libuv-1.9.1 already installed
Warning: snappy-1.1.3 already installed
Warning: protobuf-2.6.1 already installed

> Log

MB:upscaledb-2.2.0 fmgdias$ uname -a
Darwin MB.local 14.5.0 Darwin Kernel Version 14.5.0: Sun Sep 25 22:07:15 PDT 2016; root:xnu-2782.50.9~1/RELEASE_X86_64 x86_64
MB:upscaledb-2.2.0 fmgdias$ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-apple-darwin14.5.0
checking host system type... x86_64-apple-darwin14.5.0
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for gcc option to accept ISO C99... none needed
checking for gcc option to accept ISO Standard C... (cached) none needed
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking for a sed that does not truncate output... /usr/bin/sed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for an ANSI C-conforming const... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for size_t... yes
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for ar... ar
checking the archiver (ar) interface... ar
checking whether make supports nested variables... (cached) yes
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /Library/Developer/CommandLineTools/usr/bin/ld
checking if the linker (/Library/Developer/CommandLineTools/usr/bin/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm
checking the name lister (/usr/bin/nm) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 196608
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-apple-darwin14.5.0 file names to x86_64-apple-darwin14.5.0 format... func_convert_file_noop
checking how to convert x86_64-apple-darwin14.5.0 file names to toolchain format... func_convert_file_noop
checking for /Library/Developer/CommandLineTools/usr/bin/ld option to reload object files... -r
checking for objdump... no
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... no
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm output from gcc object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for lipo... lipo
checking for otool... otool
checking for otool64... no
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking for -force_load linker flag... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... yes
checking for gcc option to produce PIC... -fno-common -DPIC
checking if gcc PIC flag -fno-common -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin14.5.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /Library/Developer/CommandLineTools/usr/bin/ld
checking if the linker (/Library/Developer/CommandLineTools/usr/bin/ld) is GNU ld... no
checking whether the g++ linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking for g++ option to produce PIC... -fno-common -DPIC
checking if g++ PIC flag -fno-common -DPIC works... yes
checking if g++ static flag -static works... no
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin14.5.0 dyld
checking how to hardcode library paths into programs... immediate
checking for off_t... yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/param.h... yes
checking for getpagesize... yes
checking for working mmap... yes
checking for mmap... yes
checking for munmap... yes
checking for madvise... yes
checking for getpagesize... (cached) yes
checking for fdatasync... yes
checking for fsync... yes
checking for writev... yes
checking for pread... yes
checking for pwrite... yes
checking for posix_fadvise... no
checking for usleep... yes
checking for sched_yield... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking for unistd.h... (cached) yes
checking uv.h usability... yes
checking uv.h presence... yes
checking for uv.h... yes
checking whether the compiler supports GCC C++ ABI name demangling... yes
checking for Boost headers version >= 1.53.0... yes
checking for Boost's header version... 1_61
checking for the toolset name used by Boost for g++... xgcc42 -xgcc
checking boost/system/error_code.hpp usability... yes
checking boost/system/error_code.hpp presence... yes
checking for boost/system/error_code.hpp... yes
checking for the Boost system library... yes
checking for boost/system/error_code.hpp... (cached) yes
checking for the Boost system library... (cached) yes
checking boost/filesystem/path.hpp usability... yes
checking boost/filesystem/path.hpp presence... yes
checking for boost/filesystem/path.hpp... yes
checking for the Boost filesystem library... (cached) yes
checking for the flags needed to use pthreads... 
checking for boost/system/error_code.hpp... (cached) yes
checking for the Boost system library... (cached) yes
checking boost/thread.hpp usability... yes
checking boost/thread.hpp presence... yes
checking for boost/thread.hpp... yes
checking for the Boost thread library... (cached) yes
checking for EVP_EncryptInit_ex in -lcrypto... yes
checking openssl/evp.h usability... yes
checking openssl/evp.h presence... yes
checking for openssl/evp.h... yes
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking snappy.h usability... yes
checking snappy.h presence... yes
checking for snappy.h... yes
grep: /proc/cpuinfo: No such file or directory
grep: /proc/cpuinfo: No such file or directory
checking if google protocol buffers are installed... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating src/2protobuf/Makefile
config.status: creating src/2protoserde/Makefile
config.status: creating include/Makefile
config.status: creating include/ups/Makefile
config.status: creating samples/Makefile
config.status: creating unittests/Makefile
config.status: creating 3rdparty/Makefile
config.status: creating 3rdparty/json/Makefile
config.status: creating tools/Makefile
config.status: creating tools/ups_bench/Makefile
config.status: creating src/5server/Makefile
config.status: creating java/Makefile
config.status: creating java/java/Makefile
config.status: creating java/src/Makefile
config.status: creating java/unittests/Makefile
config.status: creating 3rdparty/liblzf/Makefile
config.status: creating 3rdparty/murmurhash3/Makefile
config.status: creating 3rdparty/simdcomp/Makefile
config.status: creating 3rdparty/streamvbyte/Makefile
config.status: creating 3rdparty/varint/Makefile
config.status: creating 3rdparty/for/Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
#================================================================
# Configuring upscaledb version 2.2.0
# Settings: (encryption) (zlib) (snappy) (no simd-sse4) (no simd-sse2) (no java) (remote)
#
# The Java API is not built because you specified
# --disable-java or because $JDK is not set
#================================================================
protoc ./messages.proto --cpp_out=.
protoc ./export.proto --cpp_out=.
g++ -fPIC -shared -o plugin.so plugin.cc -I../include -I../include -I../src -DUPS_ENABLE_REMOTE
MB:upscaledb-2.2.0 fmgdias$ make
/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
Making all in 3rdparty
Making all in liblzf
make[3]: Nothing to be done for `all'.
Making all in murmurhash3
make[3]: Nothing to be done for `all'.
Making all in for
make[3]: Nothing to be done for `all'.
Making all in json
make[3]: Nothing to be done for `all'.
make[3]: Nothing to be done for `all-am'.
Making all in src
Making all in 2protoserde
make[3]: Nothing to be done for `all'.
Making all in 2protobuf
  CXX      messages.pb.lo
  CXXLD    libprotocol.la
Making all in 5server
  CXX      upsserver.lo
upsserver.cc:2046:5: error: no matching function for call to 'uv_read_start'
    uv_read_start((uv_stream_t *)client, on_alloc_buffer, on_read_data);
    ^~~~~~~~~~~~~
/usr/local/include/uv.h:466:15: note: candidate function not viable: no known conversion from 'uv_buf_t (uv_handle_t *, size_t)' to 'uv_alloc_cb'
      (aka 'void (*)(uv_handle_t *, size_t, uv_buf_t *)') for 2nd argument
UV_EXTERN int uv_read_start(uv_stream_t*,
              ^
upsserver.cc:2093:15: error: no matching function for call to 'uv_ip4_addr'
  bind_addr = uv_ip4_addr("0.0.0.0", config->port);
              ^~~~~~~~~~~
/usr/local/include/uv.h:1371:15: note: candidate function not viable: requires 3 arguments, but 2 were provided
UV_EXTERN int uv_ip4_addr(const char* ip, int port, struct sockaddr_in* addr);
              ^
upsserver.cc:2094:3: error: no matching function for call to 'uv_tcp_bind'
  uv_tcp_bind(&srv->server, bind_addr);
  ^~~~~~~~~~~
/usr/local/include/uv.h:529:15: note: candidate function not viable: requires 3 arguments, but 2 were provided
UV_EXTERN int uv_tcp_bind(uv_tcp_t* handle,
              ^
upsserver.cc:2110:3: error: no matching function for call to 'uv_async_init'
  uv_async_init(srv->loop, &srv->async, on_async_cb);
  ^~~~~~~~~~~~~
/usr/local/include/uv.h:765:15: note: candidate function not viable: no known conversion from 'void (uv_async_t *, int)' to 'uv_async_cb' (aka 'void (*)(uv_async_t *)') for 3rd
      argument
UV_EXTERN int uv_async_init(uv_loop_t*,
              ^
4 errors generated.
make[3]: *** [upsserver.lo] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
MB:upscaledb-2.2.0 fmgdias$

**Comment by fmgdias** [comment]
Without the libuv, the build worked, but without the RemoteDatabase feature.
=(

**Comment by cruppstahl** [comment]
That's because libuv has had API changes... Here are your options:

- use upscaledb branch topic/2.2.1; it removed libuv as dependency and replaced it with boost asio (this branch is stable and will be released in the next days)

- compile libuv in version 0.11.24

Best regards
Christoph
