### ISSUE TITLE
CentOS 6.8 - Error Compile tools/ups_bench/ - instantiated from here

### ISSUE THREAD

**Issue by fmgdias** [cruppstahl/upscaledb#94]
> [root@SERVER ups_bench]# make
  CXX      main.o
In file included from /usr/local/include/boost/filesystem/path_traits.hpp:22,
                 from /usr/local/include/boost/filesystem/path.hpp:25,
                 from /usr/local/include/boost/filesystem.hpp:16,
                 from main.cc:24:
/usr/local/include/boost/type_traits/decay.hpp: In instantiation of ‘boost::decay<Configuration::<anonymous enum> >’:
main.cc:1100:   instantiated from here
/usr/local/include/boost/type_traits/decay.hpp:35: error: ‘Configuration::<anonymous enum>’ is/uses anonymous type
/usr/local/include/boost/type_traits/decay.hpp:35: error:   trying to instantiate ‘template<class T> struct boost::remove_reference’
/usr/local/include/boost/type_traits/decay.hpp:37: error: ‘Configuration::<anonymous enum>’ is/uses anonymous type
/usr/local/include/boost/type_traits/decay.hpp:37: error:   trying to instantiate ‘template<class T> struct boost::remove_reference’
make: *** [main.o] Error 1
[root@SERVER ups_bench]#

**Comment by cruppstahl** [comment]
Thanks, i will have a look over the weekend.

**Comment by cruppstahl** [comment]
I pushed a fix to topic/2.2.1. Please let me know if it works for you.
