### ISSUE TITLE
download links not working

### ISSUE THREAD

**Issue by ilovezfs** [cruppstahl/upscaledb#95]
It looks like the server for your downloads is offline. http://files.upscaledb.com/dl/upscaledb-2.2.0.tar.gz doesn't seem to work. I'm seeing the same locally and on our CI: https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/406/version=sierra/testReport/junit/brew-test-bot/sierra/fetch_upscaledb/

```
Error Message

failed: brew fetch --retry upscaledb --build-bottle --force

Stacktrace

        ==> Downloading http://files.upscaledb.com/dl/upscaledb-2.2.0.tar.gz
==> Retrying download
==> Downloading http://files.upscaledb.com/dl/upscaledb-2.2.0.tar.gz
Error: Failed to download resource "upscaledb"
Download failed: http://files.upscaledb.com/dl/upscaledb-2.2.0.tar.gz
```

**Comment by cruppstahl** [comment]
A DNS issue - should be fixed. Thanks for reporting.
